name: CI

on:
  push:
    branches:
      - feat/**
      - fix/**
      - ci/**
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create environments.ts for tests
        run: |
          mkdir -p src/environments
          cat > src/environments/environments.ts << 'EOF'
          export const environments = {
            VITE_COUNTRIES_API_URL: 'https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets',
            VITE_GOOGLE_MAPS_ID: '',
            GOOGLE_MAPS_API_KEY: ''
          };
          EOF

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests (Jest)
        run: npm run test:ci

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          if-no-files-found: ignore
